version: '3.8'

services:
  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3000
      - AUTH_TOKEN=NoumanTest
    ports:
      - "3000:3000"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"
