version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    environment:
      - PORT=3000
      - AUTH_TOKEN=NoumanTest
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app
    environment:
      - PORT=3001
      - REACT_APP_SOCKET_SERVER_URL=http://127.0.0.1:3000
    ports:
      - "3001:3001"
